// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"pr-reviewer/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPullRequestService creates a new instance of MockPullRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestService {
	mock := &MockPullRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullRequestService is an autogenerated mock type for the PullRequestService type
type MockPullRequestService struct {
	mock.Mock
}

type MockPullRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestService) EXPECT() *MockPullRequestService_Expecter {
	return &MockPullRequestService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPullRequestService
func (_mock *MockPullRequestService) Create(ctx context.Context, pr domain.PullRequest) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PullRequest) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PullRequest) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PullRequest) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPullRequestService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pr domain.PullRequest
func (_e *MockPullRequestService_Expecter) Create(ctx interface{}, pr interface{}) *MockPullRequestService_Create_Call {
	return &MockPullRequestService_Create_Call{Call: _e.mock.On("Create", ctx, pr)}
}

func (_c *MockPullRequestService_Create_Call) Run(run func(ctx context.Context, pr domain.PullRequest)) *MockPullRequestService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PullRequest
		if args[1] != nil {
			arg1 = args[1].(domain.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestService_Create_Call) Return(pullRequest *domain.PullRequest, err error) *MockPullRequestService_Create_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestService_Create_Call) RunAndReturn(run func(ctx context.Context, pr domain.PullRequest) (*domain.PullRequest, error)) *MockPullRequestService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type MockPullRequestService
func (_mock *MockPullRequestService) Merge(ctx context.Context, prID string) (*domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 *domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestService_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockPullRequestService_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPullRequestService_Expecter) Merge(ctx interface{}, prID interface{}) *MockPullRequestService_Merge_Call {
	return &MockPullRequestService_Merge_Call{Call: _e.mock.On("Merge", ctx, prID)}
}

func (_c *MockPullRequestService_Merge_Call) Run(run func(ctx context.Context, prID string)) *MockPullRequestService_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestService_Merge_Call) Return(pullRequest *domain.PullRequest, err error) *MockPullRequestService_Merge_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestService_Merge_Call) RunAndReturn(run func(ctx context.Context, prID string) (*domain.PullRequest, error)) *MockPullRequestService_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// Reassign provides a mock function for the type MockPullRequestService
func (_mock *MockPullRequestService) Reassign(ctx context.Context, prID string, oldReviewerID string) (*domain.PullRequest, string, error) {
	ret := _mock.Called(ctx, prID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for Reassign")
	}

	var r0 *domain.PullRequest
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.PullRequest, string, error)); ok {
		return returnFunc(ctx, prID, oldReviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, oldReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, prID, oldReviewerID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, prID, oldReviewerID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPullRequestService_Reassign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reassign'
type MockPullRequestService_Reassign_Call struct {
	*mock.Call
}

// Reassign is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
func (_e *MockPullRequestService_Expecter) Reassign(ctx interface{}, prID interface{}, oldReviewerID interface{}) *MockPullRequestService_Reassign_Call {
	return &MockPullRequestService_Reassign_Call{Call: _e.mock.On("Reassign", ctx, prID, oldReviewerID)}
}

func (_c *MockPullRequestService_Reassign_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string)) *MockPullRequestService_Reassign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullRequestService_Reassign_Call) Return(pullRequest *domain.PullRequest, s string, err error) *MockPullRequestService_Reassign_Call {
	_c.Call.Return(pullRequest, s, err)
	return _c
}

func (_c *MockPullRequestService_Reassign_Call) RunAndReturn(run func(ctx context.Context, prID string, oldReviewerID string) (*domain.PullRequest, string, error)) *MockPullRequestService_Reassign_Call {
	_c.Call.Return(run)
	return _c
}
