// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"pr-reviewer/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamService is an autogenerated mock type for the TeamService type
type MockTeamService struct {
	mock.Mock
}

type MockTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamService) EXPECT() *MockTeamService_Expecter {
	return &MockTeamService_Expecter{mock: &_m.Mock}
}

// AddTeam provides a mock function for the type MockTeamService
func (_mock *MockTeamService) AddTeam(ctx context.Context, team domain.Team) (*domain.Team, error) {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for AddTeam")
	}

	var r0 *domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) (*domain.Team, error)); ok {
		return returnFunc(ctx, team)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) *domain.Team); ok {
		r0 = returnFunc(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Team) error); ok {
		r1 = returnFunc(ctx, team)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamService_AddTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeam'
type MockTeamService_AddTeam_Call struct {
	*mock.Call
}

// AddTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team domain.Team
func (_e *MockTeamService_Expecter) AddTeam(ctx interface{}, team interface{}) *MockTeamService_AddTeam_Call {
	return &MockTeamService_AddTeam_Call{Call: _e.mock.On("AddTeam", ctx, team)}
}

func (_c *MockTeamService_AddTeam_Call) Run(run func(ctx context.Context, team domain.Team)) *MockTeamService_AddTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Team
		if args[1] != nil {
			arg1 = args[1].(domain.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamService_AddTeam_Call) Return(team1 *domain.Team, err error) *MockTeamService_AddTeam_Call {
	_c.Call.Return(team1, err)
	return _c
}

func (_c *MockTeamService_AddTeam_Call) RunAndReturn(run func(ctx context.Context, team domain.Team) (*domain.Team, error)) *MockTeamService_AddTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function for the type MockTeamService
func (_mock *MockTeamService) GetTeam(ctx context.Context, teamName string) (*domain.Team, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamService_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamService_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamService_Expecter) GetTeam(ctx interface{}, teamName interface{}) *MockTeamService_GetTeam_Call {
	return &MockTeamService_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamName)}
}

func (_c *MockTeamService_GetTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamService_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamService_GetTeam_Call) Return(team *domain.Team, err error) *MockTeamService_GetTeam_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamService_GetTeam_Call) RunAndReturn(run func(ctx context.Context, teamName string) (*domain.Team, error)) *MockTeamService_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}
