// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"pr-reviewer/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetReviewPullRequests provides a mock function for the type MockUserService
func (_mock *MockUserService) GetReviewPullRequests(ctx context.Context, userID string) ([]domain.PullRequestShort, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewPullRequests")
	}

	var r0 []domain.PullRequestShort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.PullRequestShort, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.PullRequestShort); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PullRequestShort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetReviewPullRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewPullRequests'
type MockUserService_GetReviewPullRequests_Call struct {
	*mock.Call
}

// GetReviewPullRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserService_Expecter) GetReviewPullRequests(ctx interface{}, userID interface{}) *MockUserService_GetReviewPullRequests_Call {
	return &MockUserService_GetReviewPullRequests_Call{Call: _e.mock.On("GetReviewPullRequests", ctx, userID)}
}

func (_c *MockUserService_GetReviewPullRequests_Call) Run(run func(ctx context.Context, userID string)) *MockUserService_GetReviewPullRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetReviewPullRequests_Call) Return(pullRequestShorts []domain.PullRequestShort, err error) *MockUserService_GetReviewPullRequests_Call {
	_c.Call.Return(pullRequestShorts, err)
	return _c
}

func (_c *MockUserService_GetReviewPullRequests_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.PullRequestShort, error)) *MockUserService_GetReviewPullRequests_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function for the type MockUserService
func (_mock *MockUserService) SetActive(ctx context.Context, userID string, isActive bool) (*domain.User, error) {
	ret := _mock.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.User, error)); ok {
		return returnFunc(ctx, userID, isActive)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *domain.User); ok {
		r0 = returnFunc(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockUserService_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockUserService_Expecter) SetActive(ctx interface{}, userID interface{}, isActive interface{}) *MockUserService_SetActive_Call {
	return &MockUserService_SetActive_Call{Call: _e.mock.On("SetActive", ctx, userID, isActive)}
}

func (_c *MockUserService_SetActive_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockUserService_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_SetActive_Call) Return(user *domain.User, err error) *MockUserService_SetActive_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_SetActive_Call) RunAndReturn(run func(ctx context.Context, userID string, isActive bool) (*domain.User, error)) *MockUserService_SetActive_Call {
	_c.Call.Return(run)
	return _c
}
