// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"pr-reviewer/internal/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPullRequestRepository creates a new instance of MockPullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type MockPullRequestRepository struct {
	mock.Mock
}

type MockPullRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestRepository) EXPECT() *MockPullRequestRepository_Expecter {
	return &MockPullRequestRepository_Expecter{mock: &_m.Mock}
}

// CreatePullRequest provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) CreatePullRequest(ctx context.Context, pr domain.PullRequest) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PullRequest) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PullRequest) domain.PullRequest); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PullRequest) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockPullRequestRepository_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - pr domain.PullRequest
func (_e *MockPullRequestRepository_Expecter) CreatePullRequest(ctx interface{}, pr interface{}) *MockPullRequestRepository_CreatePullRequest_Call {
	return &MockPullRequestRepository_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, pr)}
}

func (_c *MockPullRequestRepository_CreatePullRequest_Call) Run(run func(ctx context.Context, pr domain.PullRequest)) *MockPullRequestRepository_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PullRequest
		if args[1] != nil {
			arg1 = args[1].(domain.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_CreatePullRequest_Call) Return(pullRequest domain.PullRequest, err error) *MockPullRequestRepository_CreatePullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_CreatePullRequest_Call) RunAndReturn(run func(ctx context.Context, pr domain.PullRequest) (domain.PullRequest, error)) *MockPullRequestRepository_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullRequestByID provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetPullRequestByID(ctx context.Context, prID string) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByID")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetPullRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestByID'
type MockPullRequestRepository_GetPullRequestByID_Call struct {
	*mock.Call
}

// GetPullRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPullRequestRepository_Expecter) GetPullRequestByID(ctx interface{}, prID interface{}) *MockPullRequestRepository_GetPullRequestByID_Call {
	return &MockPullRequestRepository_GetPullRequestByID_Call{Call: _e.mock.On("GetPullRequestByID", ctx, prID)}
}

func (_c *MockPullRequestRepository_GetPullRequestByID_Call) Run(run func(ctx context.Context, prID string)) *MockPullRequestRepository_GetPullRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetPullRequestByID_Call) Return(pullRequest domain.PullRequest, err error) *MockPullRequestRepository_GetPullRequestByID_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_GetPullRequestByID_Call) RunAndReturn(run func(ctx context.Context, prID string) (domain.PullRequest, error)) *MockPullRequestRepository_GetPullRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByReviewer provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) ListByReviewer(ctx context.Context, reviewerID string) ([]domain.PullRequestShort, error) {
	ret := _mock.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByReviewer")
	}

	var r0 []domain.PullRequestShort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.PullRequestShort, error)); ok {
		return returnFunc(ctx, reviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.PullRequestShort); ok {
		r0 = returnFunc(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PullRequestShort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_ListByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByReviewer'
type MockPullRequestRepository_ListByReviewer_Call struct {
	*mock.Call
}

// ListByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID string
func (_e *MockPullRequestRepository_Expecter) ListByReviewer(ctx interface{}, reviewerID interface{}) *MockPullRequestRepository_ListByReviewer_Call {
	return &MockPullRequestRepository_ListByReviewer_Call{Call: _e.mock.On("ListByReviewer", ctx, reviewerID)}
}

func (_c *MockPullRequestRepository_ListByReviewer_Call) Run(run func(ctx context.Context, reviewerID string)) *MockPullRequestRepository_ListByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_ListByReviewer_Call) Return(pullRequestShorts []domain.PullRequestShort, err error) *MockPullRequestRepository_ListByReviewer_Call {
	_c.Call.Return(pullRequestShorts, err)
	return _c
}

func (_c *MockPullRequestRepository_ListByReviewer_Call) RunAndReturn(run func(ctx context.Context, reviewerID string) ([]domain.PullRequestShort, error)) *MockPullRequestRepository_ListByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// MergePullRequest provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) MergePullRequest(ctx context.Context, prID string, mergedAt time.Time) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, mergedAt)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, mergedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, mergedAt)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, prID, mergedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_MergePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePullRequest'
type MockPullRequestRepository_MergePullRequest_Call struct {
	*mock.Call
}

// MergePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - mergedAt time.Time
func (_e *MockPullRequestRepository_Expecter) MergePullRequest(ctx interface{}, prID interface{}, mergedAt interface{}) *MockPullRequestRepository_MergePullRequest_Call {
	return &MockPullRequestRepository_MergePullRequest_Call{Call: _e.mock.On("MergePullRequest", ctx, prID, mergedAt)}
}

func (_c *MockPullRequestRepository_MergePullRequest_Call) Run(run func(ctx context.Context, prID string, mergedAt time.Time)) *MockPullRequestRepository_MergePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_MergePullRequest_Call) Return(pullRequest domain.PullRequest, err error) *MockPullRequestRepository_MergePullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_MergePullRequest_Call) RunAndReturn(run func(ctx context.Context, prID string, mergedAt time.Time) (domain.PullRequest, error)) *MockPullRequestRepository_MergePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewer provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, oldReviewerID, newReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_ReassignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewer'
type MockPullRequestRepository_ReassignReviewer_Call struct {
	*mock.Call
}

// ReassignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
//   - newReviewerID string
func (_e *MockPullRequestRepository_Expecter) ReassignReviewer(ctx interface{}, prID interface{}, oldReviewerID interface{}, newReviewerID interface{}) *MockPullRequestRepository_ReassignReviewer_Call {
	return &MockPullRequestRepository_ReassignReviewer_Call{Call: _e.mock.On("ReassignReviewer", ctx, prID, oldReviewerID, newReviewerID)}
}

func (_c *MockPullRequestRepository_ReassignReviewer_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string)) *MockPullRequestRepository_ReassignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_ReassignReviewer_Call) Return(pullRequest domain.PullRequest, err error) *MockPullRequestRepository_ReassignReviewer_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_ReassignReviewer_Call) RunAndReturn(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (domain.PullRequest, error)) *MockPullRequestRepository_ReassignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) UpdateStatus(ctx context.Context, prID string, status domain.PullRequestStatus) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.PullRequestStatus) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.PullRequestStatus) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, status)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.PullRequestStatus) error); ok {
		r1 = returnFunc(ctx, prID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockPullRequestRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - status domain.PullRequestStatus
func (_e *MockPullRequestRepository_Expecter) UpdateStatus(ctx interface{}, prID interface{}, status interface{}) *MockPullRequestRepository_UpdateStatus_Call {
	return &MockPullRequestRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, prID, status)}
}

func (_c *MockPullRequestRepository_UpdateStatus_Call) Run(run func(ctx context.Context, prID string, status domain.PullRequestStatus)) *MockPullRequestRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.PullRequestStatus
		if args[2] != nil {
			arg2 = args[2].(domain.PullRequestStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_UpdateStatus_Call) Return(pullRequest domain.PullRequest, err error) *MockPullRequestRepository_UpdateStatus_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, prID string, status domain.PullRequestStatus) (domain.PullRequest, error)) *MockPullRequestRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
