// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"pr-reviewer/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// GetTeamByName provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetTeamByName(ctx context.Context, teamName string) (domain.Team, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Team, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Team); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetTeamByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByName'
type MockTeamRepository_GetTeamByName_Call struct {
	*mock.Call
}

// GetTeamByName is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamRepository_Expecter) GetTeamByName(ctx interface{}, teamName interface{}) *MockTeamRepository_GetTeamByName_Call {
	return &MockTeamRepository_GetTeamByName_Call{Call: _e.mock.On("GetTeamByName", ctx, teamName)}
}

func (_c *MockTeamRepository_GetTeamByName_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamByName_Call) Return(team domain.Team, err error) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetTeamByName_Call) RunAndReturn(run func(ctx context.Context, teamName string) (domain.Team, error)) *MockTeamRepository_GetTeamByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTeam provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) UpsertTeam(ctx context.Context, team domain.Team) (domain.Team, error) {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTeam")
	}

	var r0 domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) (domain.Team, error)); ok {
		return returnFunc(ctx, team)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) domain.Team); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Team) error); ok {
		r1 = returnFunc(ctx, team)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_UpsertTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTeam'
type MockTeamRepository_UpsertTeam_Call struct {
	*mock.Call
}

// UpsertTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team domain.Team
func (_e *MockTeamRepository_Expecter) UpsertTeam(ctx interface{}, team interface{}) *MockTeamRepository_UpsertTeam_Call {
	return &MockTeamRepository_UpsertTeam_Call{Call: _e.mock.On("UpsertTeam", ctx, team)}
}

func (_c *MockTeamRepository_UpsertTeam_Call) Run(run func(ctx context.Context, team domain.Team)) *MockTeamRepository_UpsertTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Team
		if args[1] != nil {
			arg1 = args[1].(domain.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_UpsertTeam_Call) Return(team1 domain.Team, err error) *MockTeamRepository_UpsertTeam_Call {
	_c.Call.Return(team1, err)
	return _c
}

func (_c *MockTeamRepository_UpsertTeam_Call) RunAndReturn(run func(ctx context.Context, team domain.Team) (domain.Team, error)) *MockTeamRepository_UpsertTeam_Call {
	_c.Call.Return(run)
	return _c
}
