// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"pr-reviewer/internal/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTx creates a new instance of MockTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTx {
	mock := &MockTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTx is an autogenerated mock type for the Tx type
type MockTx struct {
	mock.Mock
}

type MockTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTx) EXPECT() *MockTx_Expecter {
	return &MockTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockTx
func (_mock *MockTx) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTx_Expecter) Commit(ctx interface{}) *MockTx_Commit_Call {
	return &MockTx_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockTx_Commit_Call) Run(run func(ctx context.Context)) *MockTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTx_Commit_Call) Return(err error) *MockTx_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequest provides a mock function for the type MockTx
func (_mock *MockTx) CreatePullRequest(ctx context.Context, pr domain.PullRequest) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PullRequest) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PullRequest) domain.PullRequest); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PullRequest) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockTx_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - pr domain.PullRequest
func (_e *MockTx_Expecter) CreatePullRequest(ctx interface{}, pr interface{}) *MockTx_CreatePullRequest_Call {
	return &MockTx_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, pr)}
}

func (_c *MockTx_CreatePullRequest_Call) Run(run func(ctx context.Context, pr domain.PullRequest)) *MockTx_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PullRequest
		if args[1] != nil {
			arg1 = args[1].(domain.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_CreatePullRequest_Call) Return(pullRequest domain.PullRequest, err error) *MockTx_CreatePullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockTx_CreatePullRequest_Call) RunAndReturn(run func(ctx context.Context, pr domain.PullRequest) (domain.PullRequest, error)) *MockTx_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullRequestByID provides a mock function for the type MockTx
func (_mock *MockTx) GetPullRequestByID(ctx context.Context, prID string) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByID")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_GetPullRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestByID'
type MockTx_GetPullRequestByID_Call struct {
	*mock.Call
}

// GetPullRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockTx_Expecter) GetPullRequestByID(ctx interface{}, prID interface{}) *MockTx_GetPullRequestByID_Call {
	return &MockTx_GetPullRequestByID_Call{Call: _e.mock.On("GetPullRequestByID", ctx, prID)}
}

func (_c *MockTx_GetPullRequestByID_Call) Run(run func(ctx context.Context, prID string)) *MockTx_GetPullRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_GetPullRequestByID_Call) Return(pullRequest domain.PullRequest, err error) *MockTx_GetPullRequestByID_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockTx_GetPullRequestByID_Call) RunAndReturn(run func(ctx context.Context, prID string) (domain.PullRequest, error)) *MockTx_GetPullRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByName provides a mock function for the type MockTx
func (_mock *MockTx) GetTeamByName(ctx context.Context, teamName string) (domain.Team, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Team, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Team); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_GetTeamByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByName'
type MockTx_GetTeamByName_Call struct {
	*mock.Call
}

// GetTeamByName is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTx_Expecter) GetTeamByName(ctx interface{}, teamName interface{}) *MockTx_GetTeamByName_Call {
	return &MockTx_GetTeamByName_Call{Call: _e.mock.On("GetTeamByName", ctx, teamName)}
}

func (_c *MockTx_GetTeamByName_Call) Run(run func(ctx context.Context, teamName string)) *MockTx_GetTeamByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_GetTeamByName_Call) Return(team domain.Team, err error) *MockTx_GetTeamByName_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTx_GetTeamByName_Call) RunAndReturn(run func(ctx context.Context, teamName string) (domain.Team, error)) *MockTx_GetTeamByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockTx
func (_mock *MockTx) GetUserByID(ctx context.Context, userID string) (domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockTx_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTx_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockTx_GetUserByID_Call {
	return &MockTx_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockTx_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockTx_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_GetUserByID_Call) Return(user domain.User, err error) *MockTx_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockTx_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (domain.User, error)) *MockTx_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByTeam provides a mock function for the type MockTx
func (_mock *MockTx) ListActiveByTeam(ctx context.Context, teamName string) ([]domain.User, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByTeam")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.User, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.User); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_ListActiveByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByTeam'
type MockTx_ListActiveByTeam_Call struct {
	*mock.Call
}

// ListActiveByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTx_Expecter) ListActiveByTeam(ctx interface{}, teamName interface{}) *MockTx_ListActiveByTeam_Call {
	return &MockTx_ListActiveByTeam_Call{Call: _e.mock.On("ListActiveByTeam", ctx, teamName)}
}

func (_c *MockTx_ListActiveByTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockTx_ListActiveByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_ListActiveByTeam_Call) Return(users []domain.User, err error) *MockTx_ListActiveByTeam_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockTx_ListActiveByTeam_Call) RunAndReturn(run func(ctx context.Context, teamName string) ([]domain.User, error)) *MockTx_ListActiveByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ListByReviewer provides a mock function for the type MockTx
func (_mock *MockTx) ListByReviewer(ctx context.Context, reviewerID string) ([]domain.PullRequestShort, error) {
	ret := _mock.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByReviewer")
	}

	var r0 []domain.PullRequestShort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.PullRequestShort, error)); ok {
		return returnFunc(ctx, reviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.PullRequestShort); ok {
		r0 = returnFunc(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PullRequestShort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_ListByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByReviewer'
type MockTx_ListByReviewer_Call struct {
	*mock.Call
}

// ListByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID string
func (_e *MockTx_Expecter) ListByReviewer(ctx interface{}, reviewerID interface{}) *MockTx_ListByReviewer_Call {
	return &MockTx_ListByReviewer_Call{Call: _e.mock.On("ListByReviewer", ctx, reviewerID)}
}

func (_c *MockTx_ListByReviewer_Call) Run(run func(ctx context.Context, reviewerID string)) *MockTx_ListByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_ListByReviewer_Call) Return(pullRequestShorts []domain.PullRequestShort, err error) *MockTx_ListByReviewer_Call {
	_c.Call.Return(pullRequestShorts, err)
	return _c
}

func (_c *MockTx_ListByReviewer_Call) RunAndReturn(run func(ctx context.Context, reviewerID string) ([]domain.PullRequestShort, error)) *MockTx_ListByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// MergePullRequest provides a mock function for the type MockTx
func (_mock *MockTx) MergePullRequest(ctx context.Context, prID string, mergedAt time.Time) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, mergedAt)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, mergedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, mergedAt)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, prID, mergedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_MergePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePullRequest'
type MockTx_MergePullRequest_Call struct {
	*mock.Call
}

// MergePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - mergedAt time.Time
func (_e *MockTx_Expecter) MergePullRequest(ctx interface{}, prID interface{}, mergedAt interface{}) *MockTx_MergePullRequest_Call {
	return &MockTx_MergePullRequest_Call{Call: _e.mock.On("MergePullRequest", ctx, prID, mergedAt)}
}

func (_c *MockTx_MergePullRequest_Call) Run(run func(ctx context.Context, prID string, mergedAt time.Time)) *MockTx_MergePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_MergePullRequest_Call) Return(pullRequest domain.PullRequest, err error) *MockTx_MergePullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockTx_MergePullRequest_Call) RunAndReturn(run func(ctx context.Context, prID string, mergedAt time.Time) (domain.PullRequest, error)) *MockTx_MergePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewer provides a mock function for the type MockTx
func (_mock *MockTx) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, oldReviewerID, newReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, prID, oldReviewerID, newReviewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_ReassignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewer'
type MockTx_ReassignReviewer_Call struct {
	*mock.Call
}

// ReassignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
//   - newReviewerID string
func (_e *MockTx_Expecter) ReassignReviewer(ctx interface{}, prID interface{}, oldReviewerID interface{}, newReviewerID interface{}) *MockTx_ReassignReviewer_Call {
	return &MockTx_ReassignReviewer_Call{Call: _e.mock.On("ReassignReviewer", ctx, prID, oldReviewerID, newReviewerID)}
}

func (_c *MockTx_ReassignReviewer_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string)) *MockTx_ReassignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTx_ReassignReviewer_Call) Return(pullRequest domain.PullRequest, err error) *MockTx_ReassignReviewer_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockTx_ReassignReviewer_Call) RunAndReturn(run func(ctx context.Context, prID string, oldReviewerID string, newReviewerID string) (domain.PullRequest, error)) *MockTx_ReassignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockTx
func (_mock *MockTx) Rollback(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTx_Expecter) Rollback(ctx interface{}) *MockTx_Rollback_Call {
	return &MockTx_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockTx_Rollback_Call) Run(run func(ctx context.Context)) *MockTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTx_Rollback_Call) Return(err error) *MockTx_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_Rollback_Call) RunAndReturn(run func(ctx context.Context) error) *MockTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function for the type MockTx
func (_mock *MockTx) SetActive(ctx context.Context, userID string, isActive bool) (domain.User, error) {
	ret := _mock.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (domain.User, error)); ok {
		return returnFunc(ctx, userID, isActive)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) domain.User); ok {
		r0 = returnFunc(ctx, userID, isActive)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockTx_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockTx_Expecter) SetActive(ctx interface{}, userID interface{}, isActive interface{}) *MockTx_SetActive_Call {
	return &MockTx_SetActive_Call{Call: _e.mock.On("SetActive", ctx, userID, isActive)}
}

func (_c *MockTx_SetActive_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockTx_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_SetActive_Call) Return(user domain.User, err error) *MockTx_SetActive_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockTx_SetActive_Call) RunAndReturn(run func(ctx context.Context, userID string, isActive bool) (domain.User, error)) *MockTx_SetActive_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTx
func (_mock *MockTx) UpdateStatus(ctx context.Context, prID string, status domain.PullRequestStatus) (domain.PullRequest, error) {
	ret := _mock.Called(ctx, prID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 domain.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.PullRequestStatus) (domain.PullRequest, error)); ok {
		return returnFunc(ctx, prID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.PullRequestStatus) domain.PullRequest); ok {
		r0 = returnFunc(ctx, prID, status)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.PullRequestStatus) error); ok {
		r1 = returnFunc(ctx, prID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTx_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - status domain.PullRequestStatus
func (_e *MockTx_Expecter) UpdateStatus(ctx interface{}, prID interface{}, status interface{}) *MockTx_UpdateStatus_Call {
	return &MockTx_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, prID, status)}
}

func (_c *MockTx_UpdateStatus_Call) Run(run func(ctx context.Context, prID string, status domain.PullRequestStatus)) *MockTx_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.PullRequestStatus
		if args[2] != nil {
			arg2 = args[2].(domain.PullRequestStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_UpdateStatus_Call) Return(pullRequest domain.PullRequest, err error) *MockTx_UpdateStatus_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockTx_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, prID string, status domain.PullRequestStatus) (domain.PullRequest, error)) *MockTx_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTeam provides a mock function for the type MockTx
func (_mock *MockTx) UpsertTeam(ctx context.Context, team domain.Team) (domain.Team, error) {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTeam")
	}

	var r0 domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) (domain.Team, error)); ok {
		return returnFunc(ctx, team)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) domain.Team); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Team) error); ok {
		r1 = returnFunc(ctx, team)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_UpsertTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTeam'
type MockTx_UpsertTeam_Call struct {
	*mock.Call
}

// UpsertTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team domain.Team
func (_e *MockTx_Expecter) UpsertTeam(ctx interface{}, team interface{}) *MockTx_UpsertTeam_Call {
	return &MockTx_UpsertTeam_Call{Call: _e.mock.On("UpsertTeam", ctx, team)}
}

func (_c *MockTx_UpsertTeam_Call) Run(run func(ctx context.Context, team domain.Team)) *MockTx_UpsertTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Team
		if args[1] != nil {
			arg1 = args[1].(domain.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_UpsertTeam_Call) Return(team1 domain.Team, err error) *MockTx_UpsertTeam_Call {
	_c.Call.Return(team1, err)
	return _c
}

func (_c *MockTx_UpsertTeam_Call) RunAndReturn(run func(ctx context.Context, team domain.Team) (domain.Team, error)) *MockTx_UpsertTeam_Call {
	_c.Call.Return(run)
	return _c
}
