// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"pr-reviewer/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Begin(ctx context.Context) (repository.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 repository.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (repository.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) repository.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUnitOfWork_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockUnitOfWork_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Begin(ctx interface{}) *MockUnitOfWork_Begin_Call {
	return &MockUnitOfWork_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockUnitOfWork_Begin_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Begin_Call) Return(tx repository.Tx, err error) *MockUnitOfWork_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockUnitOfWork_Begin_Call) RunAndReturn(run func(ctx context.Context) (repository.Tx, error)) *MockUnitOfWork_Begin_Call {
	_c.Call.Return(run)
	return _c
}
