// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"pr-reviewer/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetUserByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByID(ctx context.Context, userID string) (domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(user domain.User, err error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (domain.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByTeam provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ListActiveByTeam(ctx context.Context, teamName string) ([]domain.User, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByTeam")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.User, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.User); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_ListActiveByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByTeam'
type MockUserRepository_ListActiveByTeam_Call struct {
	*mock.Call
}

// ListActiveByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockUserRepository_Expecter) ListActiveByTeam(ctx interface{}, teamName interface{}) *MockUserRepository_ListActiveByTeam_Call {
	return &MockUserRepository_ListActiveByTeam_Call{Call: _e.mock.On("ListActiveByTeam", ctx, teamName)}
}

func (_c *MockUserRepository_ListActiveByTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockUserRepository_ListActiveByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_ListActiveByTeam_Call) Return(users []domain.User, err error) *MockUserRepository_ListActiveByTeam_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_ListActiveByTeam_Call) RunAndReturn(run func(ctx context.Context, teamName string) ([]domain.User, error)) *MockUserRepository_ListActiveByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetActive(ctx context.Context, userID string, isActive bool) (domain.User, error) {
	ret := _mock.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (domain.User, error)); ok {
		return returnFunc(ctx, userID, isActive)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) domain.User); ok {
		r0 = returnFunc(ctx, userID, isActive)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockUserRepository_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockUserRepository_Expecter) SetActive(ctx interface{}, userID interface{}, isActive interface{}) *MockUserRepository_SetActive_Call {
	return &MockUserRepository_SetActive_Call{Call: _e.mock.On("SetActive", ctx, userID, isActive)}
}

func (_c *MockUserRepository_SetActive_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockUserRepository_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_SetActive_Call) Return(user domain.User, err error) *MockUserRepository_SetActive_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_SetActive_Call) RunAndReturn(run func(ctx context.Context, userID string, isActive bool) (domain.User, error)) *MockUserRepository_SetActive_Call {
	_c.Call.Return(run)
	return _c
}
